--- 
queuetastic: !map:HashWithIndifferentAccess 
  ast_server: localhost
  ast_port: "5038"
  queue_log: /home/jayson/asterisk_queue_logs/queue_log
  username: queuemanager
  service_level: "60.0"
  secret: secret420
